dist:
  - xenial

language:
  - cpp

sudo:
  - false

os:
  - linux

addons:
  apt:
    packages:
      - wget
      - libsndfile-dev
      - libboost-all-dev
      
script:
  - make -f build/linux/Makefile.linux64
  - ( cd tests ; make )
  
